# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Cenzor_design/Cenzor_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Cenzor_design || ORIG_REF_NAME==Cenzor_design} -quiet] -quiet

# IP: bd/Cenzor_design/ip/Cenzor_design_Cenzor_ip_0_0/Cenzor_design_Cenzor_ip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Cenzor_design_Cenzor_ip_0_0 || ORIG_REF_NAME==Cenzor_design_Cenzor_ip_0_0} -quiet] -quiet

# IP: bd/Cenzor_design/ip/Cenzor_design_processing_system7_0_0/Cenzor_design_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Cenzor_design_processing_system7_0_0 || ORIG_REF_NAME==Cenzor_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/Cenzor_design/ip/Cenzor_design_auto_pc_0/Cenzor_design_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Cenzor_design_auto_pc_0 || ORIG_REF_NAME==Cenzor_design_auto_pc_0} -quiet] -quiet

# IP: bd/Cenzor_design/ip/Cenzor_design_ps7_0_axi_periph_0/Cenzor_design_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Cenzor_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==Cenzor_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Cenzor_design/ip/Cenzor_design_rst_ps7_0_50M_0/Cenzor_design_rst_ps7_0_50M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Cenzor_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==Cenzor_design_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: bd/Cenzor_design/Cenzor_design_ooc.xdc
