# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/semestr8/SDUP/Projekt2/Zynq/Cenzor/Cenzor.srcs/sources_1/bd/Cenzor_design/ip/Cenzor_design_auto_pc_0/Cenzor_design_auto_pc_0.xci
# IP: The module: 'Cenzor_design_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/semestr8/SDUP/Projekt2/Zynq/Cenzor/Cenzor.srcs/sources_1/bd/Cenzor_design/ip/Cenzor_design_auto_pc_0/Cenzor_design_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Cenzor_design_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/semestr8/SDUP/Projekt2/Zynq/Cenzor/Cenzor.srcs/sources_1/bd/Cenzor_design/ip/Cenzor_design_auto_pc_0/Cenzor_design_auto_pc_0.xci
# IP: The module: 'Cenzor_design_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/semestr8/SDUP/Projekt2/Zynq/Cenzor/Cenzor.srcs/sources_1/bd/Cenzor_design/ip/Cenzor_design_auto_pc_0/Cenzor_design_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Cenzor_design_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
